/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_hairyd_NativeFunc */

#ifndef _Included_com_android_hairyd_NativeFunc
#define _Included_com_android_hairyd_NativeFunc
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_android_hairyd_NativeFunc
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_hairyd_NativeFunc_getStringFromNative
  (JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_android_hairyd_NativeFunc_FindFeatures(JNIEnv*, jobject, jlong addrGray, jlong addrRgba);



#ifdef __cplusplus
}
#endif
#endif
